platform :ios, '7.1'
pod 'Parse'
pod 'ParseUI'
pod 'Colours'
pod 'DateTools'
pod 'AFNetworking'
pod 'SVProgressHUD', :head
pod 'MSDynamicsDrawerViewController'
pod 'TTTAttributedLabel'
pod 'JT3DScrollView', '~> 1.0'